import "../index.html";
import "./module-a.js";
import "./module-b.js";
import "../sass/main.scss";
import "../images/clipart.png";
import "../images/dm.png";
import "../images/instagram.png";
import "../images/parque-grande.jpg";
import "../images/lightweight.svg";
